# https://en.bitcoin.it/wiki/Protocol_documentation
# https://karpathy.github.io/2021/06/21/blockchain/
# https://en.bitcoin.it/w/images/en/9/9b/PubKeyToAddr.png
# https://developer.bitcoin.org/devguide/transactions.html
# https://developer.bitcoin.org/reference/transactions.html
# https://en.wikipedia.org/wiki/Base64
# https://en.bitcoinwiki.org/wiki/Base58
# https://github.com/bitcoinbook/bitcoinbook
# https://github.com/jimmysong/programmingbitcoin
# https://developers.ledger.com/docs/nano-app/psd-applications/
# https://github.com/trezor/python-mnemonic
# https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki
# https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki
# https://github.com/bitcoin/bips/blob/master/bip-0043.mediawiki
# https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki
# https://en.bitcoin.it/wiki/OP_CHECKSIG
# http://www.righto.com/2014/02/bitcoins-hard-way-using-raw-bitcoin.html