log_level="error"
network="mainnet"

datadir=""
seeds=[]

bind="0.0.0.0:10101"
max_outgoing_peers=10
max_incoming_peers=25

input_format="hex"
output_format="hex"

# connection to bitcoind daemon
rpc_url=""
rpc_user=""
rpc_password=""
rpc_datadir=""
