name: Build and Test
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install .
          pip install pytest pytest-cov
      - name: Configure legacy algos openssl v3
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo sed -i 's/#openssl_conf = openssl_init/openssl_conf = openssl_init/' /etc/ssl/openssl.cnf
          echo ".include /etc/ssl/openssl-custom.cnf" | sudo tee -a /etc/ssl/openssl.cnf
          cat <<EOF | sudo tee /etc/ssl/openssl-custom.cnf
          [provider_sect]
          default = default_sect
          legacy = legacy_sect

          [default_sect]
          activate = 1

          [legacy_sect]
          activate = 1
          EOF
      - name: Test with pytest
        run: |
          pytest
